package com.treb.hosts.pro.events;


public enum Event {
    SAVE_HOST_LIST, REFRESH_LIST, ERROR_SAVING_LIST, SAVE_COMPLETE, SCROLL_TO_INDEX, NOTHING_FOUND, LOADING_FILE, LOADING_FINISHED, UPDATE_ENTRY, NEW_ENTRY_SAVE, EXISTING_ENTRY_SAVE, NEW_ENTRY_CANCEL, FAIL_TO_SAVE, BACKUP_COMPLETE, RESTORE_COMPLETE, REFRESH_BACKUPS, RESTORING_BACKUP, DELETING_BACKUP, ERROR, SEARCH_CANCEL, SEARCH_GO;
}
